
logging:
  level:
    root: ${APP_LOGGING_LEVEL:-INFO}
    sample.mybatis.mapper: WARN
    uk.gov.dft.bluebadge.service: ${APP_LOGGING_LEVEL:-DEBUG}
    org.springframework.security: DEBUG

management:
  server:
    port: 8481
    servlet:
      context-path: /manage
  endpoints:
    web:
      exposure:
        include: '*'

mybatis:
  type-aliases-package: uk.gov.dft.bluebadge.service.message.repository.domain
  type-handlers-package: uk.gov.dft.bluebadge.service.message.repository

spring:
  datasource:
     ***REMOVED***
    username: developer
    url: jdbc:postgresql://127.0.0.1:5432/bb_dev?currentSchema=message
  jackson:
    date-format: uk.gov.dft.bluebadge.common.api.RFC3339DateFormat
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8480
  servlet:
    context-path: /uk-gov-dft/message-service/1.0.0

springfox.documentation.swagger.v2.path: /api-docs
