blue-badge:
  auth-server:
    url: https://api.${bb_env}.${url}/bb_auth
  notify: 
    secretEnv: ${bb_env}  
     ***REMOVED***

management:
  server:
    port: ${bb_health:8081}

spring:
  main:
    banner-mode: "off"
  datasource:
     ***REMOVED***
    username: ${bb_db_username}
    url: jdbc:postgresql://${RDS_HOSTNAME}:5432/${bb_database}?currentSchema=message&sslmode=verify-full

server:
  port: ${bb_port:8080}


