blue-badge:
  auth-server:
    url: http://authorisation-service:8380/bb_auth
  notify:
    secretEnv: ${bb_env}
     ***REMOVED***
  referencedataservice:
    servicehost:
      host: referencedata-service
spring:
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:postgresql://postgresql:5432/bb_dev?currentSchema=message&sslmode=require

