blue-badge:
  auth-server:
    url: http://localhost:8380/bb_auth
    client-id: bb_user_management_id
     ***REMOVED***
  notify:
    secretEnv: dev
     ***REMOVED***
    templates:
      NEW_USER: a364e3cb-a72b-41fa-b28f-e7317525d028
      RESET_PASSWORD: 2ee75a54-8adc-41aa-ac06-5dfd724f48cb
      PASSWORD_RESET_SUCCESS: ea020bfb-cde8-4605-8726-248a38cc6bf2
      APPLICATION_SUBMITTED: e24af96c-1534-4c1e-81ad-74f2e7d9305a
      SAVE_AND_RETURN: 46da8da9-7547-4c11-838c-3a54778656d0
  reference-data-service:
    service-host:
      host: localhost
      port: 8580
      scheme: http
      connectiontimeout: 6000
      requesttimeout: 6000
      contextpath: /uk-gov-dft/reference-data-service/1.0.0
      versionaccept: application/vnd.bluebadge-api.v1+json, application/json

logging:
  level:
    root: ${APP_LOGGING_LEVEL:INFO}
    sample.mybatis.mapper: WARN
    uk.gov.dft.bluebadge.service: ${APP_LOGGING_LEVEL:DEBUG}

management:
  server:
    port: 8481
    servlet:
      context-path: /manage
  endpoints:
    web:
      exposure:
        include: '*'

mybatis:
  type-aliases-package: uk.gov.dft.bluebadge.service.message.repository.domain
  type-handlers-package: uk.gov.dft.bluebadge.common.repository

spring:
  datasource:
     ***REMOVED***
    username: developer
    url: jdbc:postgresql://127.0.0.1:5432/bb_dev?currentSchema=message
  jackson:
    date-format: uk.gov.dft.bluebadge.common.api.RFC3339DateFormat
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8480
  servlet:
    context-path: /uk-gov-dft/message-service/1.0.0

springfox.documentation.swagger.v2.path: /api-docs
