blue-badge:
  auth-server:
    url: https://authorisation-service.${bb_env}.${url}/bb_auth
    client-id: bb_user_management_id
     ***REMOVED***
  notify:
     ***REMOVED***
    templates:
      NEW_USER: a364e3cb-a72b-41fa-b28f-e7317525d028
      RESET_PASSWORD: 2ee75a54-8adc-41aa-ac06-5dfd724f48cb
      PASSWORD_RESET_SUCCESS: ea020bfb-cde8-4605-8726-248a38cc6bf2

management:
  server:
    port: ${bb_health:-8081}
    servlet:
      context-path: /manage
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  datasource:
     ***REMOVED***
    username: ${bb_db_username:-developer}
    url: jdbc:postgresql://postgres-service.${bb_env}.${url}:5432/${bb_database:-bb_dev}?currentSchema=message

server:
  port: ${bb_port:-8080}
  servlet:
    context-path: /uk-gov-dft/message-service/1.0.0

