
logging:
  level:
    root: INFO
    sample.mybatis.mapper: WARN
    uk.gov.dft.bluebadge.service: DEBUG

mybatis:
  type-aliases-package: uk.gov.dft.bluebadge.service.message.repository.domain
  type-handlers-package: uk.gov.dft.bluebadge.service.message.repository

spring:
  datasource:
     ***REMOVED***
    username: developer
    url: jdbc:postgresql://127.0.0.1:5432/bb_dev?currentSchema=usermanagement
  jackson:
    date-format: uk.gov.dft.bluebadge.service.message.RFC3339DateFormat
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8480
  servlet:
    context-path: /uk-gov-dft/message-service/1.0.0

springfox.documentation.swagger.v2.path: /api-docs
