#messageservice:
#  servicehost:
#    host: virtserver.swaggerhub.com
#    port: 80
#    scheme: http
#    connectiontimeout: 6000
#    requesttimeout: 6000
#    contextpath: /uk-gov-dft/message-service/1.0.0


messageservice:
  servicehost:
    host: localhost
    port: 8480
    scheme: http
    connectiontimeout: 6000
    requesttimeout: 6000
    contextpath: /uk-gov-dft/message-service/1.0.0

